<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>RZDirectReload.Server</RootNamespace>
    <AssemblyName>RZDirectReload.Server</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.1.0</Version>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release</Configurations>
    <DebugType>none</DebugType>
    <!-- 输出直接落在 mod 子目录，便于打包 -->
    <OutputPath>bin\$(Configuration)\$(AssemblyName)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <!-- SPT 4.1 服务端引用（NuGet 包，与官方 mod 范例一致） -->
  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
  </ItemGroup>

</Project>
